apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: leonardo-test-cert-external-secret 
  namespace: aap 
spec:
  refreshInterval: 1h
  secretStoreRef:
    kind: ClusterSecretStore
    name: azure-secret-store

  target:
    name: leonardo-test-cert-key 
    creationPolicy: Owner
    template:
      data:
        tls.crt: '{{ .cert | b64dec }}'
        tls.key: '{{ .key | b64dec }}'
      type: kubernetes.io/tls

  data:
  - secretKey: cert
    remoteRef:
      key: leonardo-test-cert

  - secretKey: key
    remoteRef:
      key: leonardo-test-key
