- name: Playbook to configure aap roles
  hosts: localhost
  connection: local
  become: false
  gather_facts: false
  vars:
    aap_organizations:
    - name: Demo-roles-org
      description: Demo org
    aap_teams:
    - name: Demo-roles-team
      organization: Demo-roles-org
    controller_roles:
      - team: Demo-roles-team
        organization: Demo-roles-org
        roles:
           - read
           - execute
      - team: Demo-roles-team
        inventory: inv1
        roles:
           - use
           - read
           
  roles:
    - infra.aap_configuration.dispatch
    
  tasks:
    - name: Create Role Definition
      ansible.controller.role_definition:
        name: test-role-def
        permissions:
          - awx.view_jobtemplate
          - awx.execute_jobtemplate
        content_type: awx.jobtemplate
        description: role definition to view and execute jt
        state: present