- name: Playbook to configure aap roles
  hosts: localhost
  connection: local
  become: false
  gather_facts: false
  vars:
    aap_organizations:
    - name: Demo-roles-org
      description: Demo org
    aap_teams:
    - name: Demo-roles-team
      organization: Demo-roles-org
    controller_roles:
      - team: Demo-roles-team
        organization: Demo-roles-org
        roles:
           - read
           - execute
  roles:
    - infra.aap_configuration.dispatch