- name: Playbook to configure ansible controller post installation
  hosts: localhost
  connection: local
  become: false
  gather_facts: false
  tasks:
  roles:
    - infra.aap_configuration.dispatch